---
title: "var1"
author: "Chris Matthis"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(usethis)
```


```{r}
#use_git()
```



```{r}
varx <- read_csv("var1.csv")

varx$var1<-factor(varx$var1, levels = c("Not at all significant", "A little bit", "Quite a bit", "Very significant"))

ggplot(varx, aes(x=var1))+
  geom_bar(fill="navy", na.rm=TRUE)+
   ggtitle("Below is a list of possible reasons precollege STEM programs might join the STEM PUSH Network. \nPlease identify how significant each factor was in your program’s motivation to join the network.\n\nObtain accreditation for broadening participation in STEM") +
  xlab("") + ylab("Count")+
  theme_classic()

```


# drop NA

```{r}
library(readr)
library(tidyverse)

varx <- read_csv("var1.csv")

varx$var1<-factor(varx$var1, levels = c("Not at all significant", "A little bit", "Quite a bit", "Very significant"))

ggplot(data=subset(varx,!is.na(var1)), aes(x=var1))+
  geom_bar(fill="navy")+
   ggtitle("Below is a list of possible reasons precollege STEM programs might join the STEM PUSH Network. \nPlease identify how significant each factor was in your program’s motivation to join the network.\n\nObtain accreditation for broadening participation in STEM") +
  xlab("") + ylab("Count")+
  theme_classic()

```


# Make bars red

```{r}
library(readr)
library(tidyverse)

varx <- read_csv("var1.csv")

varx$var1<-factor(varx$var1, levels = c("Not at all significant", "A little bit", "Quite a bit", "Very significant"))

ggplot(data=subset(varx,!is.na(var1)), aes(x=var1))+
  geom_bar(fill="orangered3")+
   ggtitle("Below is a list of possible reasons precollege STEM programs might join the STEM PUSH Network. \nPlease identify how significant each factor was in your program’s motivation to join the network.\n\nObtain accreditation for broadening participation in STEM") +
  xlab("") + ylab("Count")+
  theme_classic()

```



Another late addition.

And another.


These are the functions used to set up git and github with R.

    library(usethis)
    library(gitcreds)
    edit_git_config()
    use_git()
    gitcreds_set()
    use_github()


Later test.


